---
settings:
  config_dir: "/tmp/metrics/"
  fs_config_file_max_age: 10800
  fs_config_file_name: "ConfigLinux.json"
  fs_config_base_url: "https://gist.github.com/mkorangestripe/a40446930159849f256591a48c1c75b0/raw/"

metrics:
  - get_load_avg
  - get_uptime
  - get_cpu_metrics
  - get_mem_metrics
  - get_swap_metrics
  - get_filesystems
